print("=====Challenge 02=====")
day = input("What day were you born: ")
month = input("Month: ")
year = input("And the year: ")
print(f'You were born on the day {day}, in the month {month} and in the year {year}')